import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { BsFillMoonFill, BsLinkedin, BsTwitter, BsYoutube } from 'react-icons/bs';
import deved from '../public/dev-ed-wave.png';
export default function Home() {
 const [darkMode,setDarkMode] = useState(false)
  return (
    <div className={darkMode? 'dark': ''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-20 md:px-20 lg:px-40 dark:bg-slate-800'>
          <section className=' min-h-screen'>
            <nav className="flex  mb-12 justify-between py-10 ">
              <h1 className=' font-burtons text-2xl'>developedbyed</h1>
              <ul className='flex item-center'>
                <li>
                   <BsFillMoonFill onClick={()=>{setDarkMode(!darkMode)}} className=' cursor-pointer text-2xl' />
                </li>
                <li> <a className=' bg-gradient-to-r from-cyan-500 to-teal-50 bg px-4 text-white py-2 ml-5 rounded-md' href='#'>Resume</a> </li>
              </ul>
            </nav>
            <div className=' p-10 text-center'>
              <h2 className='py-2 text-5xl text-teal-500'>MD Tanvir</h2>
              <h3 className='text-2xl py-2 md:text-4xl'>Full Stack joniour Webdeveloper</h3>
              <p className=' text-md py-5 leading-8 text-gray-700 md:text-3xl max-w-lg mx-auto'>Freelencer Providing Service For Programming  and Website Backend develop needs. Join me down bellow and let's get Craking!</p>
            </div>
            <div className='flex justify-center text-5xl gap-10  opacity-4'>
              <BsYoutube  />
              <BsLinkedin  />
              <BsTwitter  />
            </div>
            <div objectFit="cover" layout='fill' className=' mx-auto relative bg-gradient-to-b from-teal-500 rounded-full w-88 h-88 mt-20' >
              <Image src={deved} className="py-4"  alt=""/>
            </div>

          </section>
      </main>

    </div>
  )
}
